-- Add username column initially without NOT NULL constraint
ALTER TABLE "users" ADD COLUMN "username" varchar(255);

-- Update existing users with generated usernames
-- This is a placeholder - the actual usernames will be generated by a script
UPDATE "users" SET "username" = CONCAT(
  LOWER(REPLACE("name", ' ', '')),
  '&',
  TO_CHAR(NOW(), 'YYYYMMDD'),
  '&',
  TO_CHAR(NOW(), 'HH24MISS')
) WHERE "username" IS NULL;

-- Add unique constraint
ALTER TABLE "users" ADD CONSTRAINT "users_username_unique" UNIQUE("username");

-- Now make the column NOT NULL
ALTER TABLE "users" ALTER COLUMN "username" SET NOT NULL;